server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/postgres
    username: notification_service
    password: notification_service
    hikari:
      schema: notifications

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    consumer:
      group-id: electronics-store
    bootstrap-servers: localhost:29095,localhost:29096,localhost:29097
    admin:
      auto-create: true
    topic:
      notification: electronics.store.notification.request

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/electronics-store

springdoc:
  api-docs:
    path: /notification-service/v3/api-docs
  swagger-ui:
    path: /notification-service/swagger-ui.html

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE